#!/usr/bin/env python3
"""Generate esphome/secrets.yaml with real keys.

    python tools/guardian-gen-secrets.py            # interactive
    python tools/guardian-gen-secrets.py --force    # overwrite an existing file
    python tools/guardian-gen-secrets.py --ssid X --wifi-password Y ...   # scripted

WHY THIS EXISTS

esphome/secrets.yaml.example shipped `guardian_rfid_mac_key` as 64 zeros. That
is 64 valid hex characters, so the ESPHome validator accepted it and the build
SUCCEEDED. Anyone who copied the template and filled in the fields that
obviously demanded filling - Wi-Fi, IP addresses - ended up with a fully working
system whose entire card scheme was keyed on a value published in the
repository. Every card credential derives from that key: the NTAG21x password,
and the MIFARE Classic sector keys that replace the factory FFFFFFFFFFFF on
first use.

The template now uses a non-hex sentinel so leaving it fails the build, and
validate_master_key rejects any single repeated byte. But the actual fix is to
stop asking a person to invent seven secrets by hand. This script asks only for
what it cannot know - your Wi-Fi, your addresses - and generates the rest with
the `secrets` module.

Everything it generates uses secrets.token_* / os.urandom. Nothing is derived
from a password, a hostname, the clock, or anything else guessable.
"""

import argparse
import base64
import ipaddress
import os
import re
import secrets
import stat
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "esphome", "secrets.yaml")

# Alphabet for OTA / AP passwords: unambiguous, and free of YAML-significant
# characters so a generated value never needs quoting rules thought about.
PW_ALPHABET = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def gen_password(length=32):
    return "".join(secrets.choice(PW_ALPHABET) for _ in range(length))


def gen_api_key():
    """ESPHome api.encryption.key: base64 of 32 random bytes."""
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def gen_mac_key():
    """guardian_rfid_mac_key: 32 bytes as 64 hex characters."""
    return secrets.token_hex(32)


def ask(prompt, default=None, secret=False, validate=None):
    while True:
        suffix = " [%s]" % default if default else ""
        try:
            raw = input("  %s%s: " % (prompt, suffix)).strip()
        except EOFError:
            print()
            sys.exit("\nAborted: no input available. Pass the values as flags "
                     "instead - see --help.")
        if not raw and default is not None:
            raw = default
        if not raw:
            print("    (required)")
            continue
        if validate:
            problem = validate(raw)
            if problem:
                print("    %s" % problem)
                continue
        return raw


def valid_ip(value):
    try:
        ipaddress.IPv4Address(value)
    except ValueError:
        return "Not an IPv4 address."
    return None


def valid_netmask(value):
    try:
        ipaddress.IPv4Address(value)
    except ValueError:
        return "Not an IPv4 netmask."
    return None


def build(values):
    """Render secrets.yaml. Comments carry the warnings the values cannot."""
    return """\
# Guardian ESPHome secrets - GENERATED by tools/guardian-gen-secrets.py.
#
# This file is gitignored and must never be committed. Back it up somewhere
# outside the repository: guardian_rfid_mac_key in particular is not
# regenerable without consequences (see its note below).
#
# Re-running the generator with --force replaces EVERY key here, including the
# card master key. Do not do that on a system with enrolled cards unless you
# mean to invalidate them.

# --- Shared ---
wifi_ssid: "{ssid}"
wifi_password: "{wifi_password}"

# --- Interior portal (ESP32-S3) ---
# The two encryption keys are deliberately different, so one leaked key does not
# also read the other device's API traffic.
portal_unit__encryption_key: "{portal_key}"
portal_unit__ota_password: "{portal_ota}"
portal_unit__ap_ssid: "{portal_ap_ssid}"
portal_unit__ap_password: "{portal_ap_pw}"

# --- Doorbell (Xiao ESP32-C6) ---
doorbell_unit__encryption_key: "{doorbell_key}"
doorbell_unit__ota_password: "{doorbell_ota}"
doorbell_unit__fallback_password: "{doorbell_ap_pw}"

# The address reserved for the doorbell in the router's DHCP table. Used as
# wifi.use_address so Home Assistant reaches the device by IP rather than by
# mDNS name. The device still gets its address from DHCP; this is only where
# Home Assistant looks, so the reservation and this value must agree.
doorbell_unit__ip: "{doorbell_ip}"

# Interior portal static LAN. This address must sit OUTSIDE the router's DHCP
# pool - the portal claims it statically rather than leasing it.
portal_unit__ip: "{portal_ip}"
portal_unit__gateway: "{gateway}"
portal_unit__subnet: "{subnet}"
portal_unit__dns: "{dns}"

# 32-byte HMAC key, 64 hex characters, SAME value on both devices. Generated
# with secrets.token_hex(32).
#
# READ BEFORE YOU EVER CHANGE THIS. Every card credential derives from it: the
# NTAG21x password, and the MIFARE Classic sector keys that replace the factory
# FFFFFFFFFFFF on first use. Rotating it does not merely mean "re-enroll the
# cards" - an already-upgraded Classic card ends up locked with a key nothing on
# the new install can derive. KEEP THE OLD VALUE if you ever rotate; putting it
# back is the only easy way to reach those cards again. NTAG21x cards are
# recoverable either way.
guardian_rfid_mac_key: "{mac_key}"
""".format(**values)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate esphome/secrets.yaml with cryptographically "
                    "random keys, asking only for what cannot be generated.",
    )
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing secrets.yaml. Regenerates the "
                             "card master key too, invalidating enrolled cards.")
    parser.add_argument("--out", default=TARGET, help="Output path.")
    parser.add_argument("--ssid")
    parser.add_argument("--wifi-password")
    parser.add_argument("--portal-ip")
    parser.add_argument("--doorbell-ip")
    parser.add_argument("--gateway")
    parser.add_argument("--subnet", default="255.255.255.0")
    parser.add_argument("--dns")
    parser.add_argument("--ap-ssid", default="Portal Fallback")
    args = parser.parse_args(argv)

    out = os.path.abspath(args.out)
    if os.path.exists(out) and not args.force:
        print("Refusing to overwrite an existing file:\n  %s\n" % out)
        print("Pass --force if you really mean to replace it. Note that this "
              "regenerates guardian_rfid_mac_key, which invalidates every "
              "enrolled card and can permanently lock already-upgraded MIFARE "
              "Classic cards. Back the current file up first.")
        return 1

    scripted = all([args.ssid, args.wifi_password, args.portal_ip,
                    args.doorbell_ip, args.gateway])
    if not scripted:
        print("Guardian ESPHome secrets")
        print()
        print("Every key and password is generated here. You are asked only for")
        print("the things this script cannot know: your Wi-Fi, and the two")
        print("addresses your devices will live at.")
        print()

    ssid = args.ssid or ask("Wi-Fi SSID")
    wifi_password = args.wifi_password or ask("Wi-Fi password")
    gateway = args.gateway or ask("Router / gateway IP", default="192.168.1.1",
                                  validate=valid_ip)
    portal_ip = args.portal_ip or ask(
        "Interior portal static IP (must be OUTSIDE the DHCP pool)",
        validate=valid_ip)
    doorbell_ip = args.doorbell_ip or ask(
        "Doorbell IP (must match its DHCP reservation)", validate=valid_ip)
    subnet = args.subnet if scripted else ask(
        "Subnet mask", default=args.subnet, validate=valid_netmask)
    dns = args.dns or (gateway if scripted else ask(
        "DNS server", default=gateway, validate=valid_ip))

    if portal_ip == doorbell_ip:
        print("\nThe portal and the doorbell cannot share an IP address.")
        return 1

    values = {
        "ssid": ssid,
        "wifi_password": wifi_password,
        "portal_key": gen_api_key(),
        "portal_ota": gen_password(),
        "portal_ap_ssid": args.ap_ssid,
        "portal_ap_pw": gen_password(),
        "doorbell_key": gen_api_key(),
        "doorbell_ota": gen_password(),
        "doorbell_ap_pw": gen_password(),
        "doorbell_ip": doorbell_ip,
        "portal_ip": portal_ip,
        "gateway": gateway,
        "subnet": subnet,
        "dns": dns,
        "mac_key": gen_mac_key(),
    }

    text = build(values)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    try:
        os.chmod(out, stat.S_IRUSR | stat.S_IWUSR)  # 0600 where it means anything
    except OSError:
        pass

    print()
    print("Wrote %s" % out)
    print()
    print("  7 secrets generated: 2 API encryption keys, 3 OTA/AP passwords,")
    print("  1 card master key (64 hex).")
    print()
    print("Next:")
    print("  1. Back this file up OUTSIDE the repository. guardian_rfid_mac_key")
    print("     cannot be rotated freely once cards are enrolled - the file's own")
    print("     comment explains why.")
    print("  2. Reserve %s for the doorbell in your router's DHCP table," % doorbell_ip)
    print("     and keep %s outside the DHCP pool for the portal." % portal_ip)
    print("  3. python tools/guardian-preflight.py")
    print()
    print("It is gitignored. Nothing here was printed to the terminal.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
